version: '3.9' # Docker Compose 버전

services:
  app:
    build: . # Dockerfile이 있는 경로에서 이미지 빌드
    env_file:
      - .env # 환경변수 파일 사용
    ports:
      - '${PORT}:${PORT}' # 호스트와 컨테이너의 포트를 연결
    depends_on:
      - mysql
      - mongodb
      - redis
    networks:
      - app_network
    volumes:
      - .:/usr/src/app # 소스 코드 변경 시 반영

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql # 데이터 영구 저장
    ports:
      - '3306:3306'
    networks:
      - app_network

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db # 데이터 영구 저장
    ports:
      - '27017:27017'
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app_network

# 사용자 정의 네트워크
networks:
  app_network:
    driver: bridge

# 볼륨 설정
volumes:
  mysql_data: # MySQL 데이터 저장 볼륨
  mongodb_data: # MongoDB 데이터 저장 볼륨
